[package]
name = "rustsec-cve-importer"
version = "0.1.0"
edition = "2018"
authors = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { version="0.19.2", features = [ "with-chrono-0_4", "with-serde_json-1" ] }
config = "0.10.1"
rustsec = "0.24.3"
